# Generated by Django 5.0.1 on 2024-01-29 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cita_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cliente'),
        ),
    ]
